### ISSUE TITLE
Unable to convert png files to pdf

### ISSUE THREAD

**Issue by dmlambea** [sfoxdev/docker-unoconv-alpine#1]
Trying to convert a PNG file to PDF using the container from Docker Hub fails with the following error message:

> Script started, file is /tmp/convert.log
> Verbosity set to level 3
> Using office base path: /usr/lib/libreoffice
> Using office binary path: /usr/lib/libreoffice/program
> DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
> DEBUG: Existing listener not found.
> DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
> LibreOffice listener successfully started. (pid=13)
> DEBUG: Caught exit code 81 (new installation). Restarting listener.
> DEBUG: Existing listener not found.
> DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
> LibreOffice listener successfully started. (pid=20)
> Input file: /tmp/Cafe.png
> :1: parser error : Document is empty
> �PNG
> ^
> Selected output format: Portable Document Format [.pdf]
> Selected office filter: draw_pdf_Export
> Used doctype: graphics
> Output file: file:///tmp/Cafe.pdf
> Traceback (most recent call last):
>   File "/usr/local/bin/unoconv", line 1118, in convert
>     document.storeToURL(outputurl, tuple(outputprops) )
> uno.IOException: SfxBaseModel::impl_store <file:///tmp/Cafe.pdf> failed: 0x81a
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/unoconv", line 1389, in <module>
>     main()
>   File "/usr/local/bin/unoconv", line 1305, in main
>     convertor.convert(inputfn)
>   File "/usr/local/bin/unoconv", line 1120, in convert
>     raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
>   File "/usr/lib/libreoffice/program/uno.py", line 504, in _uno_struct__getattr__
>     return getattr(self.__dict__["value"], name)
> AttributeError: ErrCode
> Script done, file is /tmp/convert.log

**Comment by dmlambea** [comment]
I've added the following extra packages to the `RUN` instruction and finally I've got successful converts:

- libreoffice-base
- libreoffice-draw
- libreoffice-calc
- libreoffice-math
- libreoffice-impress
